### ISSUE TITLE
"Open Browser" keyword crashes without error

### ISSUE THREAD

**Issue by eweseong** [robotframework/Selenium2Library#10]
I've been getting intermittent error when running a robot script, the intermittent error happens during the "Open Browser" keyword. From the VNC, the browser seems to be opened but the URL wasn't inserted into the browser. Below is the robot log and output.xml.
[log.zip](https://github.com/robotframework/Selenium2Library/files/1337380/log.zip)

**Environment Info**
operating system: Red Hat 7.2
python: 2.7
robotframework: 3.0.2
robotframework-selenium2library: 1.8.0
selenium: 3.5.0
geckodriver: 0.19.0
firefox: 55.0.3

**Comment by aaltat** [comment]
I think we did discuss this in here: https://github.com/robotframework/SeleniumLibrary/issues

Closing the issue
